### ISSUE TITLE
Build fails on macOS

### ISSUE THREAD

**Issue by benjamincburns** [VirxEC/rocketsim-rs#2]
When attempting to build this under macOS, I get the following error:

```
   × the include_cpp! macro couldn't be expanded into Rust bindings to C+
    │ +: Encountered type not yet supported by autocxx: [root :: float32_t ;
    │ 4usize]
```

This seems to be happening while building the base-level bindings for `BulletLink.h`.

I tried setting the environment variable `RUST_LOG=autocxx_engine=info` and rebuilding, and I'm extra confused by [the output](https://github.com/VirxEC/rocketsim-rs/files/10836923/build.log). It appears that it's generated a binding just fine for this type, and seems to be failing at some later step.

**Comment by VirxEC** [comment]
This should no longer be a problem, all you need to do on MacOS is disable the default `glam` feature and you're off to the races. If you still want to use the Glam crate but with portable SIMD on nightly Rust, a patch should come eventually to allow that.

**Comment by benjamincburns** [comment]
Unfortunately the build is still broken on macOS, but it's fairly trivial to fix. Will PR in just a moment
