### ISSUE TITLE
GH Actions not working for pull requests

### ISSUE THREAD

**Issue by benjamincburns** [VirxEC/rocketsim-rs#7]
We use a secret to decrypt some data files as part of the build. That secret isn't populated when the build is triggered by a `pull_request` event. There's the `pull_request_target` event that _will_ populate secrets, but this can open the door to "pwn requests" in some scenarios. Before we switch out `pull_request` for `pull_request_target` in GH actions, we should understand the security implications a bit better.

More details on this topic are here: https://securitylab.github.com/research/github-actions-preventing-pwn-requests/

**Comment by VirxEC** [comment]
We're not protecting any actually sensitive information, and as long as we aren't it shouldn't be that big of a deal. `pull_request_target` should be safe to use as "first-time contributors will require approval to run workflows" is enabled. Any pull requests must get approval before having the actions run on them, giving those with write access the time to do a quick audit of the code first and ensure there's nothing that's reading secrets at the very least.
